# This is a basic workflow that is manually triggered

name: NodeJS Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]

jobs:
  rabbitmq:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: bin/setup-rabbit.sh
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      
      - run: npm run build

      - name: run test
        run: npm run jest -- --coverage
        env: 
          TEST_BROKER_URL: 'ws://127.0.0.1:15674/ws'
          TEST_BROKER_LOGIN: 'guest'
          TEST_BROKER_PASSCODE: 'guest'

      - name: upload code coverage
        uses: codecov/codecov-action@v1.0.7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  activemq:
    runs-on: ubuntu-latest
    services:
      activemq:
        image: thedockerimages/activemq
        ports:
          - 61613:61613
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - run: npm ci
      
      - run: npm run build

      - name: run test
        run: npm run jest
        env: 
          TEST_BROKER_URL: 'ws://127.0.0.1:61613'
          TEST_BROKER_LOGIN: 'admin'
          TEST_BROKER_PASSCODE: 'nimda'
      
